DROP TABLE  IF EXISTS 	t_permission ;
CREATE TABLE t_permission  (
 id bigint(16) NOT NULL,
 permissionname VARCHAR ( 128 )  NOT NULL comment '权限名称，权限英文名称，权限编码，唯一',
 permissiondesc VARCHAR ( 128 ) DEFAULT NULL comment '权限描述，权限中文名称',
 permission_type  tinyint(4) unsigned DEFAULT 0 comment '权限类型,1：平台,2：系统，3：子系统，4：模块，5：子模块，6:一级菜单，7：二级菜单，8：三级菜单,9:页面(组件)，10：子页面（子组件），11:按钮',
 order_num  tinyint(4) unsigned DEFAULT 0 comment '排序,指的是同级顺序，拥有同一父亲时，兄弟间的顺序,0>1>2>3>4,数字小的优先',
 icon varchar(255) DEFAULT null comment '图标url',
 page_url  VARCHAR ( 1024 ) DEFAULT NULL comment '前端页面相对路径,可能为空，可能多个，多个请用逗号分隔',
 component_url  VARCHAR ( 1024 ) DEFAULT NULL comment '前端组件相对路径,比如/component/user/pageUser,可能为空，可能多个，多个请用逗号分隔',
 request_url VARCHAR ( 1024 ) DEFAULT NULL comment '后端ajax相对路径,唯一通常指ip端口后面的路径,比如/api/app/getApp或者/api/user/**,可能为空，可能多个，多个请用逗号分隔',
 parent_permission_id bigint(16) DEFAULT NULL comment '父级权限id',
 parent_permissionname VARCHAR ( 128 ) DEFAULT NULL comment '父级权限名称，父级权限英文名称，父级权限编码',
 parent_permissiondesc VARCHAR ( 128 ) DEFAULT NULL comment '父级权限描述，父级权限中文名称',
 full_permission_id VARCHAR(512) DEFAULT NULL comment '完整权限id，逗号隔开,前后都有逗号',
 full_permissionname VARCHAR ( 512 ) DEFAULT NULL comment '完整权限名称,完整权限英文名称，完整权限编码，逗号隔开,前后都有逗号',
 full_permissiondesc VARCHAR ( 512 ) DEFAULT NULL comment '完整权限描述,完整权限中文名称，页面显示的完整名称，逗号隔开,前后都有逗号',
 deep tinyint(4) unsigned  DEFAULT null comment '当前节点深度,冗余，根节点为1，第二层为为2，第三层为3，以此类推',
 status         tinyint(1) unsigned not null DEFAULT 1 comment '状态,0:禁用,1:启用',
 display           tinyint(1) unsigned not null DEFAULT 1 comment '菜单是否显示,0:隐藏,1:显示',
 create_user_id bigint(16) DEFAULT 0,
 create_user_name VARCHAR ( 128 ) DEFAULT NULL,
 create_time datetime DEFAULT NULL,
 remark text DEFAULT NULL comment '备注',
 PRIMARY KEY ( id ),
 UNIQUE KEY(permissionname),
 INDEX index_permissiondesc(permissiondesc),
 INDEX index_parent_permissionname(parent_permissionname)
) DEFAULT CHARSET=utf8mb4  comment '权限';
